<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Telegram.DotNet.Platform.Receiving</PackageId>
        <Version>9.0.0</Version>
        <Authors>bladehero</Authors>
        <PackageDescription>CTelegram.DotNet.Platform.Receiving</PackageDescription>
        <RepositoryUrl>https://github.com/bladehero/Telegram.DotNet.Platform</RepositoryUrl>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Configuration.Extensions" Version="9.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.8"/>
        <PackageReference Include="Telegram.Bot" Version="22.7.2"/>
    </ItemGroup>

</Project>