<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <Version>9.0.6</Version>
        <Authors>bladehero</Authors>
        <PackageId>Telegram.DotNet.Platform.Receiving.Background</PackageId>
        <RepositoryUrl>https://github.com/bladehero/Telegram.DotNet.Platform</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://github.com/bladehero/Telegram.DotNet.Platform</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageDescription>Telegram.DotNet.Platform.Receiving.Background</PackageDescription>
        <UserSecretsId>b5888a66-416e-4dd8-a75f-16666046d1a2</UserSecretsId>
    </PropertyGroup>
    
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.8"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Telegram.DotNet.Platform.Receiving\Telegram.DotNet.Platform.Receiving.csproj"/>
        <ProjectReference Include="..\Telegram.DotNet.Platform\Telegram.DotNet.Platform.csproj"/>
    </ItemGroup>

</Project>
