<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Telegram.DotNet.Platform.Receiving.Background</PackageId>
        <Version>9.0.0</Version>
        <Authors>bladehero</Authors>
        <PackageDescription>CTelegram.DotNet.Platform.Receiving.Background</PackageDescription>
        <RepositoryUrl>https://github.com/bladehero/Telegram.DotNet.Platform</RepositoryUrl>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.8" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.8" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Telegram.DotNet.Platform.Receiving\Telegram.DotNet.Platform.Receiving.csproj" />
      <ProjectReference Include="..\Telegram.DotNet.Platform\Telegram.DotNet.Platform.csproj" />
    </ItemGroup>

</Project>
