name: Publish to NuGet

on:
  push:
    branches: ["master"]
    tags: ["v*.*.*"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Add GitHub Packages source
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/bladehero/index.json" \
            --name bladehero \
            --username ${{ github.actor }} \
            --password ${{ secrets.GH_PAT }} \
            --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Build & Pack selected projects
        run: |
          projects=(
            "src/Telegram.DotNet.Platform/Telegram.DotNet.Platform.csproj"
            "src/Telegram.DotNet.Platform.Receiving/Telegram.DotNet.Platform.Receiving.csproj"
            "src/Telegram.DotNet.Platform.Receiving.Background/Telegram.DotNet.Platform.Receiving.Background.csproj"
          )
          for proj in "${projects[@]}"; do
            echo "📦 Packing $proj"
            dotnet restore "$proj"
            dotnet build "$proj" --configuration Release --no-restore
            dotnet pack "$proj" --configuration Release --no-build -o ./out
          done

      - name: Publish to NuGet
        run: dotnet nuget push ./out/*.nupkg --api-key ${{ secrets.GH_PAT }} --source "https://nuget.pkg.github.com/bladehero/index.json"